"""
Django settings for vuedj project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

# You need to define the following environment variables on the Host:
#
# DJANGO_SECRET_KEY
# DJANGO_ALLOWED_HOST_1  (e.g. your.site.example.com)
# DJANGO_DEBUG (True or False)
#
#
# Optional environment keys:
# DJANGO_ALLOWED_HOST_2
# DJANGO_ALLOWED_HOST_3
# DJANGO_ALLOWED_HOST_4
# DJANGO_DATABASE_NAME  (e.g. 'database1')
# DJANGO_DATABASE_USERNAME
# DJANGO_DATABASE_PASSWORD
# DJANGO_DATABASE_HOST  (must be the same name as the docker-compose service, e.g 'database1')
# DJANGO_DATABASE_PORT  (e.g. 5432)
#
# DJANGO_STATICFILES_RELATIVE_TO_BACKEND_DIRECTORY  (default = '../client/static-vuedj')
# DJANGO_STATIC_ROOT_RELATIVE_TO_BACKEND_DIRECTORY  (default = '../staticfiles/static')
# DJANGO_MEDIA_ROOT_RELATIVE_TO_BACKEND_DIRECTORY   (default = '../staticfiles/media')
# DJANGO_STATIC_URL                                 (default = '/static-vuedj/')
# DJANGO_MEDIA_URL                                  (default = '/media/')
#
#

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Project path to allow relative paths for my path variables
PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or 'weak_default_secret_key__use_DJANGO_SECRET_KEY_instead'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv('DJANGO_DEBUG') or 'True') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
if os.environ.get('DJANGO_ALLOWED_HOST_1') is not None:
	ALLOWED_HOSTS += os.environ.get('DJANGO_ALLOWED_HOST_1')
if os.environ.get('DJANGO_ALLOWED_HOST_2') is not None:
	ALLOWED_HOSTS += os.environ.get('DJANGO_ALLOWED_HOST_2')
if os.environ.get('DJANGO_ALLOWED_HOST_3') is not None:
	ALLOWED_HOSTS += os.environ.get('DJANGO_ALLOWED_HOST_3')
if os.environ.get('DJANGO_ALLOWED_HOST_4') is not None:
	ALLOWED_HOSTS += os.environ.get('DJANGO_ALLOWED_HOST_4')

CORS_ORIGIN_ALLOW_ALL = True
CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_CREDENTIALS = True

# Application definition
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sites',
	'rest_framework',
	'rest_framework.authtoken',
	'django_rest_passwordreset',
	'corsheaders',
	'allauth',
	'allauth.account',
	'allauth.socialaccount',
	'allauth.socialaccount.providers.github',
	'rest_auth',
	'rest_auth.registration',
	'api',
	'app',
	'accounts',
	'django_nose',
]


SITE_ID = 1
AUTH_USER_MODEL = 'accounts.User'
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_USER_EMAIL_FIELD = 'email'
ACCOUNT_LOGOUT_ON_GET = True
#  ACCOUNT_FORMS = {"login": "accounts.forms.UserLoginForm"}
LOGIN_REDIRECT_URL = 'home'
#  LOGIN_URL = 'api/v1/accounts/login/'

CSRF_COOKIE_NAME = "csrftoken"

REST_AUTH_SERIALIZERS = {
	"USER_DETAILS_SERIALIZER": "accounts.serializers.UserSerializer",
	#	 "LOGIN_SERIALIZER": "accounts.serializers.CustomUserLoginSerializer",
	"PASSWORD_RESET_SERIALIZER": "accounts.serializers.CustomPasswordResetSerializer"
}

REST_AUTH_REGISTER_SERIALIZERS = {
	"REGISTER_SERIALIZER": "accounts.serializers.CustomRegisterSerializer",
}

# Following is added to enable registration with email instead of username
AUTHENTICATION_BACKENDS = (
	# Needed to login by username in Django admin, regardless of `allauth`
	"django.contrib.auth.backends.ModelBackend",

	# `allauth` specific authentication methods, such as login by e-mail
	"allauth.account.auth_backends.AuthenticationBackend",
)

MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vuedj.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': ['templates/','../templates','../client/templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'vuedj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

if os.environ.get('DJANGO_DATABASE_NAME') is not None:
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.postgresql_psycopg2',
			'NAME': os.environ.get('DJANGO_DATABASE_NAME'),
			'USER': os.environ.get('DJANGO_DATABASE_USERNAME'),
			'PASSWORD': os.environ.get('DJANGO_DATABASE_PASSWORD'),
			'HOST': os.environ.get('DJANGO_DATABASE_HOST'),  # <-- IMPORTANT: same name as docker-compose service!"
			'PORT': os.environ.get('DJANGO_DATABASE_PORT'),  # e.g. 5432
		}
	}
else:
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			'NAME': os.path.join(BASE_DIR, '../db.sqlite3'),
		}
	}

REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework.authentication.TokenAuthentication',
	],
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
	],
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
	'PAGE_SIZE': 8
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATICFILES_DIRS = (
	os.path.join(BASE_DIR, (os.getenv('DJANGO_STATICFILES_RELATIVE_TO_BACKEND_DIRECTORY') or '../client/static-vuedj')),
)

STATIC_ROOT = os.path.join(BASE_DIR, (os.getenv('DJANGO_STATIC_ROOT_RELATIVE_TO_BACKEND_DIRECTORY') or '../staticfiles/static'))

MEDIA_ROOT = os.path.join(BASE_DIR, (os.getenv('DJANGO_MEDIA_ROOT_RELATIVE_TO_BACKEND_DIRECTORY') or '../staticfiles/media'))

STATIC_URL = (os.getenv('DJANGO_STATIC_URL') or '/static-vuedj/')

MEDIA_URL = (os.getenv('DJANGO_MEDIA_URL') or '/media/')

# Use nose to run all tests
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

# Tell nose to measure coverage on the apps
NOSE_ARGS = [
	'--with-coverage', # disable if tests cannot be breakpointed
	'--cover-package=accounts, api',  # For multiple apps use '--cover-package=foo, bar'
]
