# Generated by Django 2.2.5 on 2019-09-16 19:47

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('odpr_shared_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.TextWithHistory'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='bronze_badges',
            field=models.ManyToManyField(blank=True, related_name='bronze_badge_owners', to='odpr_shared_models.Badge'),
        ),
    ]
