# Generated by Django 2.2.5 on 2019-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sceneries', '0001_initial'),
        ('accounts', '0002_auto_20190916_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downloaded_sceneries',
            field=models.ManyToManyField(blank=True, related_name='scenery_downloaders', to='sceneries.Scenery'),
        ),
    ]
