# Generated by Django 2.2.5 on 2019-09-16 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('sceneries', '0001_initial'),
        ('odpr_shared_models', '0001_initial'),
        ('accounts', '0003_user_downloaded_sceneries'),
        ('scenery_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvoted_answers',
            field=models.ManyToManyField(blank=True, related_name='answer_downvoters', to='scenery_requests.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='downvoted_comments',
            field=models.ManyToManyField(blank=True, related_name='comment_downvoters', to='odpr_shared_models.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='downvoted_requests',
            field=models.ManyToManyField(blank=True, related_name='request_downvoters', to='scenery_requests.Request'),
        ),
        migrations.AddField(
            model_name='user',
            name='downvoted_sceneries',
            field=models.ManyToManyField(blank=True, related_name='scenery_downvoters', to='sceneries.Scenery'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='gold_badges',
            field=models.ManyToManyField(blank=True, related_name='gold_badge_owners', to='odpr_shared_models.Badge'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='silver_badges',
            field=models.ManyToManyField(blank=True, related_name='silver_badge_owners', to='odpr_shared_models.Badge'),
        ),
        migrations.AddField(
            model_name='user',
            name='starred_requests',
            field=models.ManyToManyField(blank=True, related_name='request_starrers', to='scenery_requests.Request'),
        ),
        migrations.AddField(
            model_name='user',
            name='starred_sceneries',
            field=models.ManyToManyField(blank=True, related_name='scenery_starrers', to='sceneries.Scenery'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_answers',
            field=models.ManyToManyField(blank=True, related_name='answer_upvoters', to='scenery_requests.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_comments',
            field=models.ManyToManyField(blank=True, related_name='comment_upvoters', to='odpr_shared_models.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_requests',
            field=models.ManyToManyField(blank=True, related_name='request_upvoters', to='scenery_requests.Request'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_sceneries',
            field=models.ManyToManyField(blank=True, related_name='scenery_upvoters', to='sceneries.Scenery'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='visited_requests',
            field=models.ManyToManyField(blank=True, related_name='request_visitors', to='scenery_requests.Request'),
        ),
        migrations.AddField(
            model_name='user',
            name='visited_sceneries',
            field=models.ManyToManyField(blank=True, related_name='scenery_visitors', to='sceneries.Scenery'),
        ),
    ]
