stages:
  - update
  - build
  - test
  - deploy

variables:
  CI_BUILDS_DIR: /
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  BUILDER_IMAGE: "docker.gitlab.electrocnic.com/dood/app/builder:latest"

services:
  - docker:dind

before_script:
  - docker info
  - chmod 755 *.sh
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.gitlab.electrocnic.com

update-runner:
  stage: update
  image: "docker:stable"
  script:
    - sh update_builder.sh

verify-build:
  stage: build
  image: $BUILDER_IMAGE
  script:
    - sh build.sh

run-tests:
  stage: test
  script:
    - sh run_tests.sh
