stages:
  - update
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  BUILDER_IMAGE: "docker.gitlab.electrocnic.com/dood/app/builder:latest"
  APP_IMAGE: "docker.gitlab.electrocnic.com/dood/app/app:latest"
  NGINX_IMAGE: "docker.gitlab.electrocnic.com/dood/app/nginx:latest"
  POSTGRES_IMAGE: "docker.gitlab.electrocnic.com/dood/app/postgres:latest"
  WORKING_DIRECTORY_ON_HOST: "/builds/dood/app"
  WORKING_DIRECTORY: "/app"
  CLIENT_DIRECTORY: "client"
  BACKEND_DIRECTORY: "backend"
  VERSION_DIRECTORY: "builder"
  GUNICORN_PORT: 8000

services:
  - docker:18.09.7-dind

before_script: &global_before_script |-
  - cd $WORKING_DIRECTORY_ON_HOST
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.gitlab.electrocnic.com

update-runner:
  stage: update
  image: "docker:18.09.7-dind"
  script:
    - sh update_builder.sh

verify-build:
  stage: build
  image: $BUILDER_IMAGE
  script:
    - sh build_gitlab.sh
    - docker build --build-arg WORKING_DIRECTORY --build-arg CLIENT_DIRECTORY --build-arg BACKEND_DIRECTORY --build-arg VERSION_DIRECTORY --build-arg GUNICORN_PORT -t $APP_IMAGE .
    - docker build -t $NGINX_IMAGE -f nginx/Dockerfile .
    - docker build -t $POSTGRES_IMAGE -f postgres/Dockerfile .
    - docker push $APP_IMAGE
    - docker push $NGINX_IMAGE
    - docker push $POSTGRES_IMAGE

run-tests:
  stage: test
  image: $APP_IMAGE
  script:
    - sh run_tests.sh
