FROM python:buster

ARG WORKING_DIRECTORY
ARG CLIENT_DIRECTORY
ARG BACKEND_DIRECTORY
ARG VERSION_DIRECTORY
ARG GUNICORN_PORT
ENV WORKING_DIRECTORY "${WORKING_DIRECTORY}"
ENV CLIENT_DIRECTORY "${CLIENT_DIRECTORY}"
ENV BACKEND_DIRECTORY "${BACKEND_DIRECTORY}"
ENV VERSION_DIRECTORY "${VERSION_DIRECTORY}"
ENV GUNICORN_PORT "${GUNICORN_PORT}"

RUN find / -iname "*backend*"
RUN pwd
RUN ls -la
COPY "${WORKING_DIRECTORY}/${BACKEND_DIRECTORY}" "${WORKING_DIRECTORY}/${BACKEND_DIRECTORY}"
COPY docker-entrypoint.sh "${WORKING_DIRECTORY}"/
# staticfiles are not copied here because the nginx-container will contain them and serve them directly


# EXPOSE port to be used
EXPOSE 80
EXPOSE 443
EXPOSE 8000

# Set command to run as soon as container is up
CMD ["${WORKING_DIRECTORY}/docker-entrypoint.sh"]
