FROM python:buster

ARG REPO_COPY_DIRECTORY
ARG CLIENT_DIRECTORY
ARG BACKEND_DIRECTORY
ARG BUILDER_VENV_DIRECTORY
ARG BUILDER_VERSION_SCRIPTS_DIRECTORY
ARG BUILDER_NODE_MODULES_SRC_DIRECTORY
ARG BUILDER_NODE_MODULES_DESTINATION_DIRECTORY
ARG BUILDER_STATIC_SRC_DIRECTORY
ARG NGINX_IMAGE_STATICFILES_DESTINATION_DIRECTORY
ARG APP_IMAGE_VENV_DIRECTORY
ARG APP_IMAGE_BACKEND_DIRECTORY
ARG DJANGO_SECRET_KEY
ARG DJANGO_DEBUG
ARG DJANGO_DATABASE_NAME
ARG DJANGO_DATABASE_USERNAME
ARG DJANGO_DATABASE_PASSWORD
ARG DJANGO_DATABASE_PORT
ARG DJANGO_DATABASE_HOST
ARG DJANGO_ALLOWED_HOST_1
ARG DJANGO_ALLOWED_HOST_2
ARG DJANGO_ALLOWED_HOST_3
ARG DJANGO_ALLOWED_HOST_4
ARG DJANGO_STATICFILES_RELATIVE_TO_BACKEND_DIRECTORY
ARG DJANGO_STATIC_ROOT_RELATIVE_TO_BACKEND_DIRECTORY
ARG DJANGO_MEDIA_ROOT_RELATIVE_TO_BACKEND_DIRECTORY
ARG DJANGO_STATIC_URL
ARG DJANGO_MEDIA_URL
ARG GUNICORN_PORT

ENV REPO_COPY_DIRECTORY "${REPO_COPY_DIRECTORY}"
ENV CLIENT_DIRECTORY "${CLIENT_DIRECTORY}"
ENV BACKEND_DIRECTORY "${BACKEND_DIRECTORY}"
ENV BUILDER_VENV_DIRECTORY "${BUILDER_VENV_DIRECTORY}"
ENV BUILDER_VERSION_SCRIPTS_DIRECTORY "${BUILDER_VERSION_SCRIPTS_DIRECTORY}"
ENV BUILDER_NODE_MODULES_SRC_DIRECTORY "${BUILDER_NODE_MODULES_SRC_DIRECTORY}"
ENV BUILDER_NODE_MODULES_DESTINATION_DIRECTORY "${BUILDER_NODE_MODULES_DESTINATION_DIRECTORY}"
ENV BUILDER_STATIC_SRC_DIRECTORY "${BUILDER_STATIC_SRC_DIRECTORY}"
ENV NGINX_IMAGE_STATICFILES_DESTINATION_DIRECTORY "${NGINX_IMAGE_STATICFILES_DESTINATION_DIRECTORY}"
ENV APP_IMAGE_VENV_DIRECTORY "${APP_IMAGE_VENV_DIRECTORY}"
ENV APP_IMAGE_BACKEND_DIRECTORY "${APP_IMAGE_BACKEND_DIRECTORY}"
ENV DJANGO_SECRET_KEY "${DJANGO_SECRET_KEY}"
ENV DJANGO_DEBUG "${DJANGO_DEBUG}"
ENV DJANGO_DATABASE_NAME "${DJANGO_DATABASE_NAME}"
ENV DJANGO_DATABASE_USERNAME "${DJANGO_DATABASE_USERNAME}"
ENV DJANGO_DATABASE_PASSWORD "${DJANGO_DATABASE_PASSWORD}"
ENV DJANGO_DATABASE_PORT "${DJANGO_DATABASE_PORT}"
ENV DJANGO_DATABASE_HOST "${DJANGO_DATABASE_HOST}"
ENV DJANGO_ALLOWED_HOST_1 "${DJANGO_ALLOWED_HOST_1}"
ENV DJANGO_ALLOWED_HOST_2 "${DJANGO_ALLOWED_HOST_2}"
ENV DJANGO_ALLOWED_HOST_3 "${DJANGO_ALLOWED_HOST_3}"
ENV DJANGO_ALLOWED_HOST_4 "${DJANGO_ALLOWED_HOST_4}"
ENV DJANGO_STATICFILES_RELATIVE_TO_BACKEND_DIRECTORY "${DJANGO_STATICFILES_RELATIVE_TO_BACKEND_DIRECTORY}"
ENV DJANGO_STATIC_ROOT_RELATIVE_TO_BACKEND_DIRECTORY "${DJANGO_STATIC_ROOT_RELATIVE_TO_BACKEND_DIRECTORY}"
ENV DJANGO_MEDIA_ROOT_RELATIVE_TO_BACKEND_DIRECTORY "${DJANGO_MEDIA_ROOT_RELATIVE_TO_BACKEND_DIRECTORY}"
ENV DJANGO_STATIC_URL "${DJANGO_STATIC_URL}"
ENV DJANGO_MEDIA_URL "${DJANGO_MEDIA_URL}"
ENV GUNICORN_PORT "${GUNICORN_PORT}"

COPY "${BUILDER_VENV_DIRECTORY}" "${APP_IMAGE_VENV_DIRECTORY}"
COPY "${BACKEND_DIRECTORY}" "${APP_IMAGE_BACKEND_DIRECTORY}"
COPY docker-entrypoint.sh /
RUN chmod 755 /docker-entrypoint.sh
# staticfiles are not copied here because the nginx-container will contain them and serve them directly


# EXPOSE port to be used
EXPOSE 80
EXPOSE 443
EXPOSE 8000

# Set command to run as soon as container is up
CMD ["/docker-entrypoint.sh"]
