'use strict'

export const scenery = 'scenery'
export const inputTitle = 'inputTitle'
export const inputDescription = 'inputDescription'
export const inputFilterpropertiesComplexity = 'inputFilterpropertiesComplexity'
export const inputEffects = 'inputEffects'
export const inputMaterials = 'inputMaterials'
export const inputLights = 'inputLights'
export const inputTags = 'inputTags'
export const inputFiles = 'inputFiles'
export const inputImages = 'inputImages'
export const errorState = 'errorState'
export const fallbackDeleteError = 'fallbackDeleteError'
export const uploadStati = 'uploadStati'
