# Generated by Django 2.2.5 on 2019-09-16 19:47

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0012_auto_20190916_2144'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odpr_shared_models', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_as_accepted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('content', annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.TextWithHistory')),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('visit_count', models.IntegerField(default=0, verbose_name='Viewed')),
                ('privacy_setting', models.IntegerField(choices=[(0, 'Public'), (1, 'Link'), (2, 'Private')], default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('description', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.TextWithHistory')),
                ('filter_properties', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='odpr_shared_models.FilterProperties')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_requests', to='odpr_shared_models.Tag')),
            ],
            options={
                'verbose_name_plural': 'Requests',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='RequestTagRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenery_requests.Request')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='RequestRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(0, 'Request Upvote'), (1, 'Request Downvote'), (2, 'Starred Request'), (3, 'Visited Request')])),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenery_requests.Request')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_request_images', to=settings.AUTH_USER_MODEL)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_preview_images', to=settings.FILER_IMAGE_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_preview_images', to='scenery_requests.Request')),
            ],
            options={
                'verbose_name_plural': 'Request Preview Images',
            },
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_request_files', to=settings.AUTH_USER_MODEL)),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_files', to='filer.File')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_files', to='scenery_requests.Request')),
            ],
            options={
                'verbose_name_plural': 'Request Files',
            },
        ),
        migrations.CreateModel(
            name='AnswerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(0, 'Answer Upvote'), (1, 'Answer Downvote')])),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenery_requests.Answer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Answer Relationships',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='parent_id',
            field=models.ForeignKey(help_text='The Request to which this answer belongs', on_delete=django.db.models.deletion.CASCADE, to='scenery_requests.Request'),
        ),
    ]
