# Generated by Django 2.1.5 on 2019-02-24 16:40

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold')])),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed', models.BooleanField(default=False, help_text='Whether the user who received this badge has viewed/seen the badge')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odpr_shared_models.Badge')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(choices=[(0, 'Posted Content'), (1, 'Posted Scenery'), (2, 'Posted Request'), (3, 'Posted Answer to a Request'), (4, 'Posted Documentation/Tutorial'), (5, 'Voted'), (6, 'Upvote'), (7, 'Downvote'), (8, 'Starred'), (9, 'Unvoted'), (10, 'Unstarred'), (11, 'Upvoted Scenery'), (12, 'Downvoted Scenery'), (13, 'Starred Scenery'), (14, 'Unvoted Scenery'), (15, 'Unstarred Scenery'), (16, 'Upvoted Request'), (17, 'Downvoted Request'), (18, 'Starred Request'), (19, 'Unvoted Request'), (20, 'Unstarred Request'), (24, 'Upvoted Comment'), (25, 'Downvoted Comment'), (26, 'Unvoted Comment'), (27, 'Posted Comment'), (28, 'Download'), (29, 'Follow'), (30, 'Blockage'), (31, 'Report'), (32, 'Reported Scenery'), (33, 'Reported Request'), (34, 'Reported User'), (35, 'Reported Answer'), (36, 'Reported Comment'), (37, 'Reported Documentation'), (38, 'Earned Points')])),
                ('condition', models.IntegerField(help_text='Amount of reputation or actions needed to grant badge')),
                ('signal_direction', models.IntegerField(choices=[(0, 'User Action will rule badge-gain of another user'), (1, 'User Action will rule badge-gain of same user'), (2, 'User Action will rule badge-gain of same user AND another user')], help_text='Whether the badgeSignal will lead to a badge on this user or on the receiving user. The receiving means, the user who will suffer from the action of this user.')),
                ('badges', models.ManyToManyField(blank=True, related_name='rules', to='odpr_shared_models.Badge')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Scenery Comment'), (1, 'Request Comment'), (2, 'Request-Answer Comment')])),
                ('parent_id', models.IntegerField(help_text='ID of either the Scenery, the Request or the Answer, to which this comment belongs (depends on configured type of the comment)')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(0, 'Comment Upvote'), (1, 'Comment Downvote')])),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comment Relationships',
            },
        ),
        migrations.CreateModel(
            name='FilterProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenery_complexity', models.IntegerField(choices=[(0, 'Minimalistic'), (1, 'Simple'), (2, 'Intermediate'), (3, 'Complex')])),
            ],
            options={
                'verbose_name_plural': 'Wrapped Filter Properties',
            },
        ),
        migrations.CreateModel(
            name='FilterProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_filter_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Filter Properties',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTextWithHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=2000, verbose_name='TextWithHistory')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical text with history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTextWithHistoryAuthor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=20000, verbose_name='TextWithHistory')),
                ('type', models.IntegerField(choices=[(0, 'Scenery Description'), (1, 'Request Description'), (2, 'Comment'), (3, 'Answer')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical text with history author',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('request_body', models.TextField(blank=True, default='')),
                ('request_method', models.CharField(default='GET', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_profile_images', to=settings.AUTH_USER_MODEL)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_images', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile Images',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'User'), (1, 'Scenery'), (2, 'Request'), (3, 'Comment'), (4, 'Answer'), (5, 'Documentation')])),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('reference', models.IntegerField(help_text='ID to scenery, request, user or comment')),
                ('resolved', models.BooleanField(default=False, help_text='Whether the report has been reviewed and some action (or not) was made')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReputationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(choices=[(0, 'Posted Content'), (1, 'Posted Scenery'), (2, 'Posted Request'), (3, 'Posted Answer to a Request'), (4, 'Posted Documentation/Tutorial'), (5, 'Voted'), (6, 'Upvote'), (7, 'Downvote'), (8, 'Starred'), (9, 'Unvoted'), (10, 'Unstarred'), (11, 'Upvoted Scenery'), (12, 'Downvoted Scenery'), (13, 'Starred Scenery'), (14, 'Unvoted Scenery'), (15, 'Unstarred Scenery'), (16, 'Upvoted Request'), (17, 'Downvoted Request'), (18, 'Starred Request'), (19, 'Unvoted Request'), (20, 'Unstarred Request'), (24, 'Upvoted Comment'), (25, 'Downvoted Comment'), (26, 'Unvoted Comment'), (27, 'Posted Comment'), (28, 'Download'), (29, 'Follow'), (30, 'Blockage'), (31, 'Report'), (32, 'Reported Scenery'), (33, 'Reported Request'), (34, 'Reported User'), (35, 'Reported Answer'), (36, 'Reported Comment'), (37, 'Reported Documentation'), (38, 'Earned Points')])),
                ('condition', models.IntegerField(help_text='Amount of reputation needed to permit User Action.')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.CharField(max_length=45)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextWithHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=2000, verbose_name='TextWithHistory')),
            ],
            options={
                'verbose_name_plural': 'Texts with History',
            },
        ),
        migrations.CreateModel(
            name='TextWithHistoryAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=20000, verbose_name='TextWithHistory')),
                ('type', models.IntegerField(choices=[(0, 'Scenery Description'), (1, 'Request Description'), (2, 'Comment'), (3, 'Answer')])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textual_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Texts with History and Details',
            },
        ),
        migrations.AddField(
            model_name='filterproperty',
            name='description',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.TextWithHistory'),
        ),
        migrations.AddField(
            model_name='filterproperties',
            name='effects',
            field=models.ManyToManyField(help_text="One or more effects (Filter for caustics). If no effect in scene: Choose Effect 'None'", related_name='effects', to='odpr_shared_models.FilterProperty'),
        ),
        migrations.AddField(
            model_name='filterproperties',
            name='lights',
            field=models.ManyToManyField(help_text="One or more lights (Filter for sceneries). If no lights in scene: Choose Light 'None'", related_name='lights', to='odpr_shared_models.FilterProperty'),
        ),
        migrations.AddField(
            model_name='filterproperties',
            name='materials',
            field=models.ManyToManyField(help_text="One or more materials (Filter for sceneries). If no material in scene: Choose Material 'None'", related_name='materials', to='odpr_shared_models.FilterProperty'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.TextWithHistory'),
        ),
    ]
