# Generated by Django 2.1.5 on 2019-02-13 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploaded at'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploaded at'),
        ),
    ]
