# Generated by Django 2.1.5 on 2019-02-24 16:40

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odpr_shared_models', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0011_auto_20190213_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('visit_count', models.IntegerField(default=0, verbose_name='Viewed')),
                ('download_count', models.IntegerField(default=0, verbose_name='Downloads')),
                ('privacy_setting', models.IntegerField(choices=[(0, 'Public'), (1, 'Link'), (2, 'Private')], default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sceneries', to=settings.AUTH_USER_MODEL)),
                ('description', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.TextWithHistory')),
                ('filter_properties', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenery', to='odpr_shared_models.FilterProperties')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_sceneries', to='odpr_shared_models.Tag')),
            ],
            options={
                'verbose_name_plural': 'Sceneries',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SceneryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_scenery_files', to=settings.AUTH_USER_MODEL)),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenery_files', to='filer.File')),
                ('scenery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenery_files', to='sceneries.Scenery')),
            ],
            options={
                'verbose_name_plural': 'Scenery Files',
            },
        ),
        migrations.CreateModel(
            name='SceneryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_scenery_images', to=settings.AUTH_USER_MODEL)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenery_preview_images', to=settings.FILER_IMAGE_MODEL)),
                ('scenery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='sceneries.Scenery')),
            ],
            options={
                'verbose_name_plural': 'Scenery Preview Images',
            },
        ),
        migrations.CreateModel(
            name='SceneryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(0, 'Scenery Upvote'), (1, 'Scenery Downvote'), (2, 'Starred Scenery'), (3, 'Visited Scenery'), (4, 'Scenery Download')])),
                ('scenery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceneries.Scenery')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SceneryTagRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceneries.Scenery')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odpr_shared_models.Tag')),
            ],
        ),
    ]
