
include /etc/nginx/sites-customizations/local.*.conf;

# first we declare our upstream server, which is our Gunicorn application
upstream app_server {
    # docker will automatically resolve this to the correct address
    # because we use the same name as the service: "app"

    server app:8000; # TODO: inject port
}
