# now we declare our main server
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name localhost;
    # return 301 https://example.com$request_uri;

		location /staticfiles/ {
        root /;
    }

    location /media/ {
        root /;
    }
}
