# now we declare our main server
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name NGINX_SERVER_NAME www.NGINX_SERVER_NAME;
    NGINX_PERMANENT_REDIRECT_INSTRUCTION

    location / {
				# everything is passed to Gunicorn
				proxy_pass http://app_server;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_set_header Host $host;
				proxy_redirect off;
				client_max_body_size 50M; # allow up to 50MB user-provided file-upload size.
		}

    location NGINX_IMAGE_STATICFILES_DESTINATION_DIRECTORY/ {
        root /;
    }

    location NGINX_IMAGE_MEDIAFILES_DESTINATION_DIRECTORY/ {
        root /;
    }
}
