# now we declare our main server
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name localhost;  # TODO: inject url depending on production mode: localhost or real domain(s).
    # return 301 https://example.com$request_uri;  # TODO: inject url and activate depending on production mode

		location / {
            # everything is passed to Gunicorn
            proxy_pass http://app_server;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
            client_max_body_size 50M; # allow up to 50MB user-provided file-upload size.
        }

		location /static-vuedj/ { # TODO: inject location
        root /;
    }

    location /media/ { # TODO: inject location
        root /;
    }
}
