'use strict'
export const stateActive = 'active'
export const stateSubmitted = 'submitted'
export const stateRegisterSuccess = 'registerSuccess'
export const stateRegisterError = 'registerError'
export const stateLoginError = 'loginError'
export const statePasswordError = 'passwordError'
export const statePasswordSuccess = 'passwordSuccess'
export const stateLoginSubmit = 'loginSubmit'
export const stateRegisterSubmit = 'registerSubmit'
export const statePasswordSubmit = 'passwordSubmit'
